import { Inter } from "next/font/google";
import "./globals.css";
import ThemeRegistry from "./theme-registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "744 Survey",
  description: "Generated by create next app",
  icons: {
    icon: '/icon.png',
    apple: '/apple-icon.png',
  }
};

export const viewport = {
  colorScheme: 'dark',
}

export default function RootLayout({ children }) {
  return (
    <ThemeRegistry  options={{ key: 'joy' }}>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </ThemeRegistry>
  );
}